repos:
  - repo: local
    hooks:
      - id: lint-repo-changed
        name: Lint repo (changed files)
        language: system
        entry: poetry run python scripts/lint/lint_repo.py --check --changed-only --no-clean
        pass_filenames: false
