---
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: consistent
    indent-sequences: whatever

ignore: |
  .venv/
  node_modules/
  outputs/
  dist/
  target/
