"""PFF Rust acceleration package."""

from ._pff_rust import (
    BloomFilter,
    RuleEncoder,
    TripleStoreSoA,
    VocabularyEncoder,
    batch_generate_negative_samples,
    check_violations_batch,
    compute_ece,
    convert_to_triples,
    degree_weighted_negative_sampling,
    fast_average_precision_score,
    fast_matthews_corrcoef,
    fast_mcc_sweep,
    fast_precision_recall_curve,
    fast_roc_auc_score,
    find_unique_triples_mask,
    generate_emu_noise,
    generate_negative_samples,
    hash_64bit,
    hash_bytes,
    hash_tuple,
    sorted_jaccard_similarity,
    stable_hash,
    string_to_ngram_hashes,
)

__all__ = [
    "BloomFilter",
    "RuleEncoder",
    "TripleStoreSoA",
    "VocabularyEncoder",
    "batch_generate_negative_samples",
    "check_violations_batch",
    "compute_ece",
    "convert_to_triples",
    "degree_weighted_negative_sampling",
    "fast_average_precision_score",
    "fast_matthews_corrcoef",
    "fast_mcc_sweep",
    "fast_precision_recall_curve",
    "fast_roc_auc_score",
    "find_unique_triples_mask",
    "generate_emu_noise",
    "generate_negative_samples",
    "hash_64bit",
    "hash_bytes",
    "hash_tuple",
    "sorted_jaccard_similarity",
    "stable_hash",
    "string_to_ngram_hashes",
]
