[package]
name = "pff-rust-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11"
rustc-hash = "2.0"
glob = "0.3"
libc = "0.2"
memmap2 = "0.9"
mimalloc = "0.1"
num_cpus = "1.16"
piz = "0.5"
polars = { version = "0.43.1", features = ["csv", "json", "parquet"] }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = "0.13"
thiserror = "1.0"
tracing = "0.1"
tracing-appender = "0.2"
tracing-indicatif = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "env-filter"] }
zstd = "0.13"
zstd-safe = "7.2"
lz4_flex = "0.11"
sonic-rs = "0.3"
memchr = "2.7"
snap = "1.1"
rkyv = "0.8"
flate2 = "1.0"

[dependencies.monoio]
version = "0.2"
optional = true

[features]
default = ["progress"]
progress = ["tracing-indicatif"]
linux_uring = ["monoio"]

[profile.release]
lto = "fat"
codegen-units = 1
